código, quantidade, valor = input().split(" ")
código2, quantidade2, valor2 = input().split(" ")
quantidade = int(quantidade)
quantidade2 = int(quantidade2)
valor = float(valor)
valor2 = float(valor2)
print(f"VALOR A PAGAR: R$ {(quantidade * valor + quantidade2 * valor2):.2f}")