A, B, C = input().split(" ")
A = float(A)
B = float(B)
C = float(C)
print(f"TRIANGULO: {((A * C) / 2):.3F}")
print(f"CIRCULO: {(C ** 2 * 3.14159):.3F}")
print(f"TRAPEZIO: {(((A + B) * C) / 2):.3F}")
print(f"QUADRADO: {(B ** 2):.3F}")
print(f"RETANGULO: {(A * B):.3F}")